package com.wyz.blog.dao;

import com.wyz.blog.dataObject.BlogArticleContent;

public interface BlogArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    int insert(BlogArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    int insertSelective(BlogArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    BlogArticleContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    int updateByPrimaryKeySelective(BlogArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(BlogArticleContent record);
}