package com.wyz.blog.dao;

import com.wyz.blog.dataObject.BlogCategory;
import com.wyz.blog.dataObject.BlogCategoryArticle;
import com.wyz.blog.entity.Category;

public interface BlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insert(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insertSelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    BlogCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_category
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKey(BlogCategory record);


    BlogCategory selectByName(String name);

    BlogCategory[] selectAll();
}