package com.wyz.blog.dao;

import com.wyz.blog.dataObject.BlogArticleComment;

public interface BlogArticleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_comment
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_comment
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insert(BlogArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_comment
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insertSelective(BlogArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_comment
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    BlogArticleComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_comment
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(BlogArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_comment
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKey(BlogArticleComment record);

    BlogArticleComment[] selectByArticleID(Integer articleId);

    BlogArticleComment[] selectByCommentId(Integer commentId);
}