package com.wyz.blog.dao;

import com.wyz.blog.dataObject.SystemVisit;

public interface SystemVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_visit
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_visit
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insert(SystemVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_visit
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insertSelective(SystemVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_visit
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    SystemVisit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_visit
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(SystemVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_visit
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKey(SystemVisit record);
}