package com.wyz.blog.dao;

import com.wyz.blog.dataObject.SystemAdminLog;

public interface SystemAdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insert(SystemAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int insertSelective(SystemAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    SystemAdminLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(SystemAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_log
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    int updateByPrimaryKey(SystemAdminLog record);
}