package com.wyz.blog.dataObject;

import java.util.Date;

public class BlogCategoryArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category_article.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category_article.category_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category_article.article_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category_article.create_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Date createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category_article.modified_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Date modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_category_article.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Boolean isEffective;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category_article.id
     *
     * @return the value of blog_category_article.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category_article.id
     *
     * @param id the value for blog_category_article.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category_article.category_id
     *
     * @return the value of blog_category_article.category_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category_article.category_id
     *
     * @param categoryId the value for blog_category_article.category_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category_article.article_id
     *
     * @return the value of blog_category_article.article_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category_article.article_id
     *
     * @param articleId the value for blog_category_article.article_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category_article.create_by
     *
     * @return the value of blog_category_article.create_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category_article.create_by
     *
     * @param createBy the value for blog_category_article.create_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category_article.modified_by
     *
     * @return the value of blog_category_article.modified_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category_article.modified_by
     *
     * @param modifiedBy the value for blog_category_article.modified_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_category_article.is_effective
     *
     * @return the value of blog_category_article.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Boolean getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_category_article.is_effective
     *
     * @param isEffective the value for blog_category_article.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setIsEffective(Boolean isEffective) {
        this.isEffective = isEffective;
    }
}