package com.wyz.blog.dataObject;

import java.util.Date;

public class BlogArticleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.title
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.traffic
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Integer traffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.create_by
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Date createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.modified_by
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Date modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.is_effective
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Boolean isEffective;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.img_url
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_info.content_id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Integer contentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.id
     *
     * @return the value of blog_article_info.id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.id
     *
     * @param id the value for blog_article_info.id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.title
     *
     * @return the value of blog_article_info.title
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.title
     *
     * @param title the value for blog_article_info.title
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.traffic
     *
     * @return the value of blog_article_info.traffic
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.traffic
     *
     * @param traffic the value for blog_article_info.traffic
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.create_by
     *
     * @return the value of blog_article_info.create_by
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.create_by
     *
     * @param createBy the value for blog_article_info.create_by
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.modified_by
     *
     * @return the value of blog_article_info.modified_by
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.modified_by
     *
     * @param modifiedBy the value for blog_article_info.modified_by
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.is_effective
     *
     * @return the value of blog_article_info.is_effective
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Boolean getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.is_effective
     *
     * @param isEffective the value for blog_article_info.is_effective
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setIsEffective(Boolean isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.img_url
     *
     * @return the value of blog_article_info.img_url
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.img_url
     *
     * @param imgUrl the value for blog_article_info.img_url
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_info.content_id
     *
     * @return the value of blog_article_info.content_id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_info.content_id
     *
     * @param contentId the value for blog_article_info.content_id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
}