package com.wyz.blog.dataObject;

import java.util.Date;

public class BlogNotify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_notify.id
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_notify.email
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_notify.create_by
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    private Date createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_notify.modified_by
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    private Date modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_notify.is_effective
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    private Boolean isEffective;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_notify.id
     *
     * @return the value of blog_notify.id
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_notify.id
     *
     * @param id the value for blog_notify.id
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_notify.email
     *
     * @return the value of blog_notify.email
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_notify.email
     *
     * @param email the value for blog_notify.email
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_notify.create_by
     *
     * @return the value of blog_notify.create_by
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_notify.create_by
     *
     * @param createBy the value for blog_notify.create_by
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_notify.modified_by
     *
     * @return the value of blog_notify.modified_by
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_notify.modified_by
     *
     * @param modifiedBy the value for blog_notify.modified_by
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_notify.is_effective
     *
     * @return the value of blog_notify.is_effective
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public Boolean getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_notify.is_effective
     *
     * @param isEffective the value for blog_notify.is_effective
     *
     * @mbg.generated Fri May 03 02:15:48 CST 2019
     */
    public void setIsEffective(Boolean isEffective) {
        this.isEffective = isEffective;
    }
}