package com.wyz.blog.dataObject;

public class BlogArticleContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_content.id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_content.content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_content.id
     *
     * @return the value of blog_article_content.id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_content.id
     *
     * @param id the value for blog_article_content.id
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_content.content
     *
     * @return the value of blog_article_content.content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_content.content
     *
     * @param content the value for blog_article_content.content
     *
     * @mbg.generated Sat May 04 15:48:30 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}