package com.wyz.blog.dataObject;

public class BlogComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.content
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.name
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.email
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.reference
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer reference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Boolean isEffective;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.is_expected
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Boolean isExpected;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.id
     *
     * @return the value of blog_comment.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.id
     *
     * @param id the value for blog_comment.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.content
     *
     * @return the value of blog_comment.content
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.content
     *
     * @param content the value for blog_comment.content
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.name
     *
     * @return the value of blog_comment.name
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.name
     *
     * @param name the value for blog_comment.name
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.email
     *
     * @return the value of blog_comment.email
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.email
     *
     * @param email the value for blog_comment.email
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.reference
     *
     * @return the value of blog_comment.reference
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.reference
     *
     * @param reference the value for blog_comment.reference
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setReference(Integer reference) {
        this.reference = reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.is_effective
     *
     * @return the value of blog_comment.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Boolean getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.is_effective
     *
     * @param isEffective the value for blog_comment.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setIsEffective(Boolean isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.is_expected
     *
     * @return the value of blog_comment.is_expected
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Boolean getIsExpected() {
        return isExpected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.is_expected
     *
     * @param isExpected the value for blog_comment.is_expected
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setIsExpected(Boolean isExpected) {
        this.isExpected = isExpected;
    }
}