package com.wyz.blog.dataObject;

import java.util.Date;

public class BlogArticleComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_comment.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_comment.article_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_comment.commont_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_comment.create_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Date createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_comment.modified_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    private Date modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_comment.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_comment.id
     *
     * @param id the value for blog_article_comment.id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_comment.article_id
     *
     * @return the value of blog_article_comment.article_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_comment.article_id
     *
     * @param articleId the value for blog_article_comment.article_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_comment.commont_id
     *
     * @return the value of blog_article_comment.commont_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_comment.commont_id
     *
     * @param commontId the value for blog_article_comment.commont_id
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setCommentId(Integer commontId) {
        this.commentId = commontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_comment.create_by
     *
     * @return the value of blog_article_comment.create_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_comment.create_by
     *
     * @param createBy the value for blog_article_comment.create_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_comment.modified_by
     *
     * @return the value of blog_article_comment.modified_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_comment.modified_by
     *
     * @param modifiedBy the value for blog_article_comment.modified_by
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_comment.is_effective
     *
     * @return the value of blog_article_comment.is_effective
     *
     * @mbg.generated Fri May 03 00:46:10 CST 2019
     */

}